# Generated by Django 6.0.7 on 2026-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/')),
                ('icon', models.CharField(default='foundation', max_length=50)),
                ('meeting_day', models.CharField(blank=True, help_text='e.g. Every Tuesday, 2:00 - 3:00 PM', max_length=100)),
                ('is_sport', models.BooleanField(default=False, help_text='Check if this is a sports/talent-development activity rather than a club.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
