# Generated by Django 6.1 on 2026-09-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended: transparent PNG or SVG-exported-as-PNG, roughly 400x120px.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='school_name',
            field=models.CharField(default='Carol and Kelly Joystar Academy', max_length=200),
        ),
    ]
